source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HeroinPlayer_Example', :exclusive => true do
  pod "HeroinPlayer", :path => "../"
end

target 'HeroinPlayer_Tests', :exclusive => true do
  pod "HeroinPlayer", :path => "../"

  
end
